FROM maven:3.8.8-eclipse-temurin-21-alpine

# Install google cloud dependencies and key
RUN apk update && apk add --no-cache bash curl python3

# Install google cloud to have access to cloud maven repo and initialize the service account

# Copy source code to be compiled
WORKDIR code
COPY .gauth/sa-key.json sa-key.json
# Install google cloud to have access to cloud maven repo and initialize the service account
RUN curl https://sdk.cloud.google.com > install.sh && bash install.sh --disable-prompts --install-dir=/code > /dev/null 2>&1
ENV PATH="$PATH:/code/google-cloud-sdk/bin"

COPY --chmod=0777 mvnw mvnw
COPY .mvn .mvn
COPY pom.xml pom.xml

# Fix CRLF line endings if present in mvnw
RUN sed -i 's/\r$//' mvnw

#Unknown lifecycle phase "/root/.m2" issue
ENV MAVEN_CONFIG=""

#RUN ./mvnw dependency:go-offline -Dmaven.repo.local=.m2
COPY src src

#ENTRYPOINT ["./mvnw", "-Dmaven.repo.local=.m2", "quarkus:test"]
ENTRYPOINT ["google-cloud-sdk/bin/gcloud auth activate-service-account image-repo-account@cn25-g15-tripmonkey.iam.gserviceaccount.com --key-file=sa-key.json --verbosity=debug","&&","./mvnw", "-Dmaven.repo.local=.m2", "test", "--no-transfer-progress"]